config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "/contact-us", to: "pages#contact", as: "contact"
  get "/schedule", to: "pages#schedule"
  get "/results", to: "pages#results"

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations" }

  resources :users
  resources :players, only: %i[index new create show edit update]
  resources :teams
  resources :divisions
  resources :contact_forms, only: %i[index new create]
  resources :blog, only: %i[show index]

  namespace :admin_center do
    root to: "dashboard#index"

    resources :dashboard, only: [:index]
    resources :teams do
      patch :add_player
    end
    resources :players
    resources :matches
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < User
	default_scope { player }

	belongs_to :team, counter_cache: true

	scope :no_team, -> { where(team_id: nil) }
	scope :not_in_division, ->(division_id) { joins(:team).where("teams.division_id != ?", division_id) }

	def name
		# TODO: Decorative method. Add to helper function or presenter instead
		"#{first_name} #{last_name}"
	end

	def team_name
		team&.name
	end
end

app/controllers/admin_center/base_controller.rb
module AdminCenter

	class BaseController < ApplicationController
		
		before_action :authenticate_user!

		layout "admin"

	end

end

app/controllers/admin_center/dashboard_controller.rb
# frozen_string_literal: true

module AdminCenter

	# AdminCenter::DashboardController
	class DashboardController < AdminCenter::BaseController
		def index; end
	end

end

app/controllers/admin_center/matches_controller.rb
# frozen_string_literal: true

module AdminCenter

	class MatchesController < AdminCenter::BaseController

		before_action :load_match, only: %i[show edit update]

		def index
			@matches = Match.joins(team_match_stats: :team).includes(team_match_stats: :team)
		end

		def new
			@match = Match.new
		end

		def create
			result = Matches::Create.call(params: params)
			
			if result.success?
				flash[:notice] = "Match created successfully"
			else
				flash[:error] = result.message
			end

			redirect_to admin_center_matches_path
		end

		def show; end

		def edit; end

		def update; end

		def destroy; end

		private

			def load_match
				@match ||= Match.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:error] = "Match with id #{params[:id]} not found"
				redirect_to admin_center_matches_path
			end

	end

end

app/controllers/admin_center/players_controller.rb
# frozen_string_literal: true

module AdminCenter

	class PlayersController < AdminCenter::BaseController

		before_action :load_player, only: %i[show edit update]

		def index
			@players = Player.all
		end

		def new
			@player = Player.new
		end

		def create
			@player = Player.create!(player_params)
			flash[:notice] = "Player created successfully"
			redirect_to admin_center_players_path
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_players_path
		end

		def show; end

		def edit; end

		def update
			@player.update!(player_params)
			flash[:notice] = "Player information updated successfully"
			redirect_to admin_center_player_path(@player)
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_player_path(@player)
		end

		protected

			def load_player
				@player = Player.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "Player with id: #{params[:id]} not found"
				redirect_to admin_center_players_path
			end

			def player_params
				params.fetch(:player, {})
					  .permit(:first_name, :last_name, :email, :date_of_birth, :status, :team_id, :password, :password_confirmation)
			end
		
	end

end

app/controllers/admin_center/teams_controller.rb
# frozen_string_literal: true

module AdminCenter

	class TeamsController < AdminCenter::BaseController

		before_action :load_team, only: %i[show edit update add_player]

		def index
			@teams = Team.all
		end

		def new
			@team = Team.new
		end

		def create
			@team = Team.new(team_params)
			@team.save!(team_params)
			flash[:notice] = "Team created successfully"
			redirect_to admin_center_teams_path
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_teams_path
		end

		def show
			@players = @team.players
			@other_players = Player.no_team
		end

		def edit; end

		def update
			@team.update(team_params)
			flash[:notice] = "Team information updated successfully"
			redirect_to admin_center_team_path(@team)
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_team_path(@team)
		end

		def add_player
			players = Player.where(id: team_params[:player_ids])
			@team.players << players
			@team.save!
			flash[:notive] = "Add player to #{team.name}"
			redirect_to admin_center_team_path(@team, anchor: "#player")
		rescue StandardError
			flash[:alert] = "Could not add player to #{@team.name}"
			redirect_to admin_center_team_path(@team, anchor: "#player")
		end

		protected

			def load_team
				@team = Team.find(params[:id] || params[:team_id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "Team with id: #{params[:id]} not found"
				redirect_to admin_center_teams_path
			end

			def team_params
				params.fetch(:team, {}).permit(:name, :division_id, :player_ids)
			end
		
	end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :check_for_user, :only => [:edit, :update]
  before_action :check_for_admin, :only => [:index]

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
    render :layout => "login_signup"
  end

  def show
  end

  def create
    @player = Player.new player_params

    if @player.save
      session[:player_id] = @player.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @player = @current_player
  end

  def update
    # :email, :dob, :image, :name, :password, :password_confirmation
    player = @current_player

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])

      player.image = req['public_id']
    end

    player.update_attributes player_params
    player.save
    redirect_to player

  end

  def destroy
  end

  private
  def player_params
    params.require(:player).permit(:email, :dob, :name, :password, :password_confirmation)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/admin_center/players/_form.html.erb
<%= form_for @player, url: admin_center_players_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name, class: "small mb-1" %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name, class: "small mb-1" %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "small mb-1" %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date_of_birth, class: "small mb-1" %>
    <%= f.date_field :date_of_birth, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :team_id, class: "small mb-1" %>
    <%= f.select :team_id, Team.pluck(:name, :id), {:prompt => 'Select Team'}, { class: "form-control" } %>
  </div>

    <div class="form-group">
	    <%= f.label :password, class: "small mb-1" %>
	    <%= f.password_field :password, class: "form-control" %>
	  </div>

    <div class="form-group">
	    <%= f.label :password_confirmation, class: "small mb-1" %>
	    <%= f.password_field :password_confirmation, class: "form-control" %>
	  </div>
  
  <%= f.submit %>
<% end %>

app/views/admin_center/players/_player.html.erb
<td><%= player.name %></td>
<td><%= player.team_name %></td>

app/views/admin_center/players/index.html.erb
<div class="container-fluid">
	<h1 class="mt-4">Players</h1>
	<ol class="breadcrumb mb-4">
	    <li class="breadcrumb-item"><%= link_to "Dashboard", admin_center_root_path %></li>
	    <li class="breadcrumb-item active">Players</li>
	</ol>
	<div class="card mb-4">
    <div class="row">
      <div class="col-sm-12 float-right">
        <%= link_to "Add Player", new_admin_center_player_path, class: "btn btn-primary float-right"%>
      </div>
    </div>
		<div class="card-header"><i class="fas fa-table mr-1"></i>Players</div>
		<div class="card-body">
	    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Name</th>
              <th>Team</th>
            </tr>
          </thead>
          <tbody>
            <% @players.each do |player| %>
              <tr>
                <%= render partial: "player", locals: { player: player } %>
              </tr>
            <% end %>
          </tbody>
        </table>
	    </div>
		</div>
	</div>
</div>

app/views/admin_center/players/new.html.erb
<div class="container-fluid">
  <h1 class="mt-4">New Player</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item"><%= link_to "Teams", admin_center_players_path %></li>
      <li class="breadcrumb-item active">New</li>
  </ol>
  <div class="row">
    <div class=col-md-6>
      <div class="card mb-4">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>