config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "/contact-us", to: "pages#contact", as: "contact"
  get "/schedule", to: "pages#schedule"
  get "/results", to: "pages#results"

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations" }

  resources :users
  resources :players, only: %i[index new create show edit update]
  resources :teams
  resources :divisions
  resources :contact_forms, only: %i[index new create]
  resources :blog, only: %i[show index]

  namespace :admin_center do
    root to: "dashboard#index"

    resources :dashboard, only: [:index]
    resources :teams do
      patch :add_player
    end
    resources :players
    resources :matches
  end
end

app/models/match.rb
# frozen_string_literal: true

class Match < ActiveRecord::Base

	STATUSES =
		{
			upcoming: "upcoming",
			played: "played",
			in_progress: "in progress",
			postponed: "postponed",
			cancelled: "cancelled"
		}

	has_many :team_match_stats
	has_many :teams, through: :team_match_stats

	enum status: STATUSES
	enum kind: { league: "league", trial: "trial" }

	def ended?
		end_at < Time.current
	end

	alias :past? :ended?

	def started?
		return if past?

		start_time = actual_start_at || start_at

		start_time >= Time.current
	end

	def start_time
		actual_start_at || start_at
	end
end

app/controllers/admin_center/base_controller.rb
module AdminCenter

	class BaseController < ApplicationController
		
		before_action :authenticate_user!

		layout "admin"

	end

end

app/controllers/admin_center/dashboard_controller.rb
# frozen_string_literal: true

module AdminCenter

	# AdminCenter::DashboardController
	class DashboardController < AdminCenter::BaseController
		def index; end
	end

end

app/controllers/admin_center/matches_controller.rb
# frozen_string_literal: true

module AdminCenter

	class MatchesController < AdminCenter::BaseController

		before_action :load_match, only: %i[show edit update]

		def index
			@matches = Match.joins(team_match_stats: :team).includes(team_match_stats: :team)
		end

		def new
			@match = Match.new
		end

		def create
			result = Matches::Create.call(params: params)
			
			if result.success?
				flash[:notice] = "Match created successfully"
			else
				flash[:error] = result.message
			end

			redirect_to admin_center_matches_path
		end

		def show; end

		def edit; end

		def update; end

		def destroy; end

		private

			def load_match
				@match ||= Match.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:error] = "Match with id #{params[:id]} not found"
				redirect_to admin_center_matches_path
			end

	end

end

app/controllers/admin_center/players_controller.rb
# frozen_string_literal: true

module AdminCenter

	class PlayersController < AdminCenter::BaseController

		before_action :load_player, only: %i[show edit update]

		def index
			@players = Player.all
		end

		def new
			@player = Player.new
		end

		def create
			@player = Player.create!(player_params)
			flash[:notice] = "Player created successfully"
			redirect_to admin_center_players_path
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_players_path
		end

		def show; end

		def edit; end

		def update
			@player.update!(player_params)
			flash[:notice] = "Player information updated successfully"
			redirect_to admin_center_player_path(@player)
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_player_path(@player)
		end

		protected

			def load_player
				@player = Player.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "Player with id: #{params[:id]} not found"
				redirect_to admin_center_players_path
			end

			def player_params
				params.fetch(:player, {})
					  .permit(:first_name, :last_name, :email, :date_of_birth, :status, :team_id, :password, :password_confirmation)
			end
		
	end

end

app/controllers/admin_center/teams_controller.rb
# frozen_string_literal: true

module AdminCenter

	class TeamsController < AdminCenter::BaseController

		before_action :load_team, only: %i[show edit update add_player]

		def index
			@teams = Team.all
		end

		def new
			@team = Team.new
		end

		def create
			@team = Team.new(team_params)
			@team.save!(team_params)
			flash[:notice] = "Team created successfully"
			redirect_to admin_center_teams_path
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_teams_path
		end

		def show
			@players = @team.players
			@other_players = Player.no_team
		end

		def edit; end

		def update
			@team.update(team_params)
			flash[:notice] = "Team information updated successfully"
			redirect_to admin_center_team_path(@team)
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_team_path(@team)
		end

		def add_player
			players = Player.where(id: team_params[:player_ids])
			@team.players << players
			@team.save!
			flash[:notive] = "Add player to #{team.name}"
			redirect_to admin_center_team_path(@team, anchor: "#player")
		rescue StandardError
			flash[:alert] = "Could not add player to #{@team.name}"
			redirect_to admin_center_team_path(@team, anchor: "#player")
		end

		protected

			def load_team
				@team = Team.find(params[:id] || params[:team_id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "Team with id: #{params[:id]} not found"
				redirect_to admin_center_teams_path
			end

			def team_params
				params.fetch(:team, {}).permit(:name, :division_id, :player_ids)
			end
		
	end

end

app/views/admin_center/matches/_form.html.erb
<%= form_tag(admin_center_matches_path) do %>
  <%= hidden_field_tag "id", params[:id] %>
  <div class="form-row">
    <div class="col-md-10 mb-1">
      <%= label_tag "first_team_id", nil, class: "small" %>
      <%= select_tag "first_team_id", options_from_collection_for_select(Team.all, "id", "name"), prompt: "Select Team", class: "form-control" %>
    </div>

    <div class="col-md-2 mb-1">
      <%= label_tag "first_team_goals", nil, class: "small" %>
      <%= number_field_tag "first_team_goals", nil, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="col-md-10 mb-1">
      <%= label_tag "second_team_id", nil, class: "small" %>
      <%= select_tag "second_team_id", options_from_collection_for_select(Team.all, "id", "name"), prompt: "Select Team", class: "form-control" %>
    </div>

    <div class="col-md-2 mb-1">
      <%= label_tag "second_team_goals", nil, class: "small" %>
      <%= number_field_tag "second_team_goals", nil, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag "kind", nil, class: "small mb-1" %>
    <%= select_tag "kind", options_for_select(Match.kinds.map { |k,v| [ k, v ] }), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "start_at", nil, class: "small mb-1" %>
    <div class='input-group date' id='datetimepicker'>
      <input type='text' class="form-control" />
      <span class="input-group-addon">
          <span class="fas fa-calendar"></span>
      </span>
    </div>
    <%#= datetime_field "start_at", nil, class: "form-control" %>
  </div>
  
  <%= submit_tag "Create Match", class: "mt-4" %>
<% end %>

app/views/admin_center/matches/_match.html.erb
<td><%= match.start_time %></td>
<td><%= match.teams.first.name %></td>

app/views/admin_center/matches/edit.html.erb
<div class="container-fluid">
  <h1 class="mt-4">Edit Match</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item"><%= link_to "Matches", admin_center_matches_path %></li>
      <li class="breadcrumb-item active">Edit</li>
  </ol>
  <div class="row">
    <div class=col-md-6>
      <div class="card mb-4">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin_center/matches/index.html.erb
<div class="container-fluid">
	<h1 class="mt-4">Players</h1>
	<ol class="breadcrumb mb-4">
	    <li class="breadcrumb-item"><%= link_to "Dashboard", admin_center_root_path %></li>
	    <li class="breadcrumb-item active">Matches</li>
	</ol>
	<div class="card mb-4">
    <div class="row">
      <div class="col-sm-12 float-right">
        <%= link_to "Add Match", new_admin_center_match_path, class: "btn btn-primary float-right"%>
      </div>
    </div>
		<div class="card-header"><i class="fas fa-table mr-1"></i>Players</div>
		<div class="card-body">
	    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Start Time</th>
              <th>Match</th>
            </tr>
          </thead>
          <tbody>
            <% @matches.each do |match| %>
              <tr>
                <%= render partial: "match", locals: { match: match } %>
              </tr>
            <% end %>
          </tbody>
        </table>
	    </div>
		</div>
	</div>
</div>

app/views/admin_center/matches/new.html.erb
<div class="container-fluid">
  <h1 class="mt-4">New Match</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item"><%= link_to "Matches", admin_center_matches_path %></li>
      <li class="breadcrumb-item active">New</li>
  </ol>
  <div class="row">
    <div class=col-md-6>
      <div class="card mb-4">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>