config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "/contact-us", to: "pages#contact", as: "contact"
  get "/schedule", to: "pages#schedule"
  get "/results", to: "pages#results"

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations" }

  resources :users
  resources :players, only: %i[index new create show edit update]
  resources :teams
  resources :divisions
  resources :contact_forms, only: %i[index new create]
  resources :blog, only: %i[show index]

  namespace :admin_center do
    root to: "dashboard#index"

    resources :dashboard, only: [:index]
    resources :teams do
      patch :add_player
    end
    resources :players
    resources :matches
  end
end

app/models/team.rb
# frozen_string_literal: true

class Team < ActiveRecord::Base
  belongs_to :division, counter_cache: true
  has_many   :players
  has_many	 :match_stats, class_name: "TeamMatchStat"
  has_many	 :matches, through: :match_stats
  has_one    :season_stat, class_name: "TeamSeasonStat"

  validates :name, presence: true
end

app/controllers/admin_center/base_controller.rb
module AdminCenter

	class BaseController < ApplicationController
		
		before_action :authenticate_user!

		layout "admin"

	end

end

app/controllers/admin_center/dashboard_controller.rb
# frozen_string_literal: true

module AdminCenter

	# AdminCenter::DashboardController
	class DashboardController < AdminCenter::BaseController
		def index; end
	end

end

app/controllers/admin_center/matches_controller.rb
# frozen_string_literal: true

module AdminCenter

	class MatchesController < AdminCenter::BaseController

		before_action :load_match, only: %i[show edit update]

		def index
			@matches = Match.joins(team_match_stats: :team).includes(team_match_stats: :team)
		end

		def new
			@match = Match.new
		end

		def create
			result = Matches::Create.call(params: params)
			
			if result.success?
				flash[:notice] = "Match created successfully"
			else
				flash[:error] = result.message
			end

			redirect_to admin_center_matches_path
		end

		def show; end

		def edit; end

		def update; end

		def destroy; end

		private

			def load_match
				@match ||= Match.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:error] = "Match with id #{params[:id]} not found"
				redirect_to admin_center_matches_path
			end

	end

end

app/controllers/admin_center/players_controller.rb
# frozen_string_literal: true

module AdminCenter

	class PlayersController < AdminCenter::BaseController

		before_action :load_player, only: %i[show edit update]

		def index
			@players = Player.all
		end

		def new
			@player = Player.new
		end

		def create
			@player = Player.create!(player_params)
			flash[:notice] = "Player created successfully"
			redirect_to admin_center_players_path
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_players_path
		end

		def show; end

		def edit; end

		def update
			@player.update!(player_params)
			flash[:notice] = "Player information updated successfully"
			redirect_to admin_center_player_path(@player)
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_player_path(@player)
		end

		protected

			def load_player
				@player = Player.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "Player with id: #{params[:id]} not found"
				redirect_to admin_center_players_path
			end

			def player_params
				params.fetch(:player, {})
					  .permit(:first_name, :last_name, :email, :date_of_birth, :status, :team_id, :password, :password_confirmation)
			end
		
	end

end

app/controllers/admin_center/teams_controller.rb
# frozen_string_literal: true

module AdminCenter

	class TeamsController < AdminCenter::BaseController

		before_action :load_team, only: %i[show edit update add_player]

		def index
			@teams = Team.all
		end

		def new
			@team = Team.new
		end

		def create
			@team = Team.new(team_params)
			@team.save!(team_params)
			flash[:notice] = "Team created successfully"
			redirect_to admin_center_teams_path
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_teams_path
		end

		def show
			@players = @team.players
			@other_players = Player.no_team
		end

		def edit; end

		def update
			@team.update(team_params)
			flash[:notice] = "Team information updated successfully"
			redirect_to admin_center_team_path(@team)
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_team_path(@team)
		end

		def add_player
			players = Player.where(id: team_params[:player_ids])
			@team.players << players
			@team.save!
			flash[:notive] = "Add player to #{team.name}"
			redirect_to admin_center_team_path(@team, anchor: "#player")
		rescue StandardError
			flash[:alert] = "Could not add player to #{@team.name}"
			redirect_to admin_center_team_path(@team, anchor: "#player")
		end

		protected

			def load_team
				@team = Team.find(params[:id] || params[:team_id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "Team with id: #{params[:id]} not found"
				redirect_to admin_center_teams_path
			end

			def team_params
				params.fetch(:team, {}).permit(:name, :division_id, :player_ids)
			end
		
	end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :check_for_admin, :only => ['new', 'edit', 'create', 'update', 'destroy']
  def new
    @team = Team.new
  end

  def create
    team = Team.create team_params

    redirect_to team
  end

  def index
    @teams = Team.all
    console
  end

  def show
    @team = Team.find params[:id]
  end

  def edit
    @team = Team.find params[:id]
  end

  def update
    team = Team.find params[:id]
    team.update team_params

    redirect_to team
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to :action => 'index'
  end

  private
  def team_params
    params.require(:team).permit(:name, :division_id)
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admin_center/teams/_form.html.erb
<%= form_for @team, url: admin_center_teams_path do |f| %>
    <div class="form-group">
      <label class="small mb-1" for="name">Name</label>
      <%= f.text_field :name, class: "form-control py-4",  placeholder: "Enter team name" %>
    </div>
    <div class="form-group">
      <label class="small mb-1" for="division">Division</label>
      <%= f.select :division_id, Division.pluck(:name, :id), class: "form-control py-4" %>
    </div>
    <%= f.submit %>
<% end %>

app/views/admin_center/teams/_player.html.erb
<td><%= player.name %></td>
<td><%= link_to "Edit", edit_admin_center_player_path(player), class: "btn btn-primary" %></td>
<td><%= link_to "Delete", admin_center_player_path(player), method: :delete, class: "btn btn-danger" %></td>

app/views/admin_center/teams/_players.html.erb
<div class="row mb-4 mt-4">
  <div class="col-md-4">
    <%= form_for @team, url: admin_center_team_add_player_path(@team), method: :patch do |f| %>
      <div class="form-group">
        <%= f.label :player_ids, "Players", class: "small mb-1" %>
        <%= f.select :player_ids, @other_players.map { |player| [player.name, player.id] }, { prompt: "Select Team" }, { class: "form-control" } %>
      </div>
      <%= f.submit "Add Player" %>
    <% end %>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="2" class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
        <tr>
          <%= render partial: "player", locals: { player: player } %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin_center/teams/_team.html.erb
<td><%= team.name %></td>
<td><%= team.division.name %></td>
<td><%= team.players_count %></td>
<td><%= link_to "Show", admin_center_team_path(team) %></td>

app/views/admin_center/teams/_teams.html.erb
<div class="card mb-4">
  <div class="row">
    <div class="col-sm-12 float-right">
      <%= link_to "Add Team", new_admin_center_team_path, class: "btn btn-primary float-right"%>
    </div>
  </div>
	<div class="card-header"><i class="fas fa-table mr-1"></i>All teams</div>
	<div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Division</th>
            <th>Number of players</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
  				<% @teams.each do |team| %>
  					<tr>
  						<%= render partial: "team", locals: { team: team } %>
  					</tr>
  				<% end %>
        </tbody>
      </table>
    </div>
	</div>
</div>

app/views/admin_center/teams/index.html.erb
<div class="container-fluid">
	<h1 class="mt-4">Teams</h1>
	<ol class="breadcrumb mb-4">
	    <li class="breadcrumb-item"><%= link_to "Dashboard", admin_center_root_path %></li>
	    <li class="breadcrumb-item active">Teams</li>
	</ol>
  <%= render "teams" %>
</div>

app/views/admin_center/teams/new.html.erb
<div class="container-fluid">
  <h1 class="mt-4">New Team</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item"><%= link_to "Teams", admin_center_teams_path %></li>
      <li class="breadcrumb-item active">New</li>
  </ol>
  <div class="row">
    <div class=col-md-6>
      <div class="card mb-4">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin_center/teams/show.html.erb
<div class="container-fluid">
  <h1 class="mt-4"><%= @team.name %></h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item"><%= link_to "Dashboard", admin_center_root_path %></li>
      <li class="breadcrumb-item"><%= link_to "Teams", admin_center_teams_path %></li>
      <li class="breadcrumb-item active"><%= @team.name %></li>
  </ol>
  <div class="card mb-4">
    <div class="card-header"><i class="fas fa-table mr-1"></i>All teams</div>
    <div class="card-body">
      <ul class="nav nav-tabs" id="teams-tab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="teams-tab" data-toggle="tab" href="#teams" role="tab" aria-controls="teams" aria-selected="true">Team info</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Team stats</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="contact-tab" data-toggle="tab" href="#players" role="tab" aria-controls="contact" aria-selected="false">Players</a>
        </li>
      </ul>
      <div class="tab-content" id="teams-content">
        <div class="tab-pane fade show active" id="teams" role="tabpanel" aria-labelledby="teams-tab">
          Here we are
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
        <div class="tab-pane fade" id="players" role="tabpanel" aria-labelledby="players-tab">
          <%= render "players" %>
        </div>
      </div>

    </div>
  </div>
</div>