config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get "/contact-us", to: "pages#contact", as: "contact"
  get "/schedule", to: "pages#schedule"
  get "/results", to: "pages#results"

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations" }

  resources :users
  resources :players, only: %i[index new create show edit update]
  resources :teams
  resources :divisions
  resources :contact_forms, only: %i[index new create]
  resources :blog, only: %i[show index]

  namespace :admin_center do
    root to: "dashboard#index"

    resources :dashboard, only: [:index]
    resources :teams do
      patch :add_player
    end
    resources :players
    resources :matches
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < User
	default_scope { player }

	belongs_to :team, counter_cache: true

	scope :no_team, -> { where(team_id: nil) }
	scope :not_in_division, ->(division_id) { joins(:team).where("teams.division_id != ?", division_id) }

	def name
		# TODO: Decorative method. Add to helper function or presenter instead
		"#{first_name} #{last_name}"
	end

	def team_name
		team&.name
	end
end

app/controllers/admin_center/players_controller.rb
# frozen_string_literal: true

module AdminCenter

	class PlayersController < AdminCenter::BaseController

		before_action :load_player, only: %i[show edit update]

		def index
			@players = Player.all
		end

		def new
			@player = Player.new
		end

		def create
			@player = Player.create!(player_params)
			flash[:notice] = "Player created successfully"
			redirect_to admin_center_players_path
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_players_path
		end

		def show; end

		def edit; end

		def update
			@player.update!(player_params)
			flash[:notice] = "Player information updated successfully"
			redirect_to admin_center_player_path(@player)
		rescue StandardError => e
			flash[:alert] = e.message
			redirect_to admin_center_player_path(@player)
		end

		protected

			def load_player
				@player = Player.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "Player with id: #{params[:id]} not found"
				redirect_to admin_center_players_path
			end

			def player_params
				params.fetch(:player, {})
					  .permit(:first_name, :last_name, :email, :date_of_birth, :status, :team_id, :password, :password_confirmation)
			end
		
	end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :check_for_user, :only => [:edit, :update]
  before_action :check_for_admin, :only => [:index]

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
    render :layout => "login_signup"
  end

  def show
  end

  def create
    @player = Player.new player_params

    if @player.save
      session[:player_id] = @player.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @player = @current_player
  end

  def update
    # :email, :dob, :image, :name, :password, :password_confirmation
    player = @current_player

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])

      player.image = req['public_id']
    end

    player.update_attributes player_params
    player.save
    redirect_to player

  end

  def destroy
  end

  private
  def player_params
    params.require(:player).permit(:email, :dob, :name, :password, :password_confirmation)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.erb
<h1>User info</h1>
<%= form_for(@player, :html => {:multipart => true},) do |f| %>
  <div class="form-inline">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-inline">
    <%= f.label :email %>
    <%= f.text_field :email, :class => 'form-control' %>
  </div>

  <div class="form-inline">
    <%= f.label :dob %>
    <%= f.text_field :dob, :class => 'form-control' %>
  </div>

  <div class="form-inline">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control' %>
  </div>

  <div class="form-inline">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>
  </div>

  <div class="form-inline">
    <%= f.label :image %>
    <%= f.cl_image_upload :image, :class => 'form-control' %>
  </div>

  <div class="form-inline">
    <%= f.label :team_id %>
    <%= f.select :team_id, Team.pluck(:name, :id), {:prompt => 'Select Team'}, {:class => 'form-control'} %>
  </div>


  <%= f.submit :class => 'btn btn-primary'%>

<% end %>

app/views/players/index.html.erb
<h1> All Players </h1>
<table class="table table-hover table-inverse">
  <tr>
    <th>Players</th>
    <th>Teams</th>
  </tr>
  <% @players.each do |player| %>
    <tr>
      <td class="player"><%= player.name %></td>
      <td class="team"><%= player.team.name %></td>
    </tr>

  <% end %>
</table>

app/views/players/new.html.erb
<div class="col-xs-4 user-form">
  <h2>Sign Up</h2>
  
  <%= form_for @player do |f| %>
    <%= f.email_field :email, :class => 'form-control', :placeholder => 'email' %>
    <%= f.password_field :password, :placeholder => 'password', :class => 'form-control' %>
    <%= f.password_field :password_confirmation, :placeholder => 'password confirmation', :class => 'form-control' %>

    <%= f.submit 'Sign up!', :class => 'btn btn-primary' %>
  <% end %>
  <p> Already have an account? <%= link_to "Login", login_path %>
</div>

app/views/players/show.html.erb
<h1>Player Profile</h1>
<ul>
  <% if @current_player.image %>
    <li class="thumb"> <%= @current_player.image %></li>
  <% end %>
  <% if @current_player.name %>
    <li><%= @current_player.name %></li>
  <% end %>
  <li><%= @current_player.email %></li>
  <% if @current_player.dob %>
    <li><%= @current_player.dob %></li>
  <% end %>

  <% if @current_player.team %>
    <li><%= link_to @current_player.team.name, team_path(@current_player.team) %></li>
  <% end %>
</ul>
<p>
  <%= link_to "Edit Profile", edit_player_path(@current_player.id) %>
</p>